version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./python_backend
    ports:
      - "3001:3001"  # Change to your backend port if needed